### PR TITLE
Fix macOS app logger crashes on Emacs

### LINKED ISSUE #84: macOS Applogger stops logging arbitrarily
## Expected Behavior
App logger keeps logging during an experiment's duration.

## Actual Behavior
app logger when stop at some point while other loggers continue to log.

## Steps to Reproduce the Problem

1. Create an experiment with an app logger and set run dates to include today
1. join the experiment
1. Give necessary permissions to TaqoLauncher to log app usage
1.  Wait and after some arbitrary amount of time or actions the app logger will stop and can only be restarted by killing and restarting the daemon.

## Specifications

- Version: 1.1.1
- Platform: macOS Catalina 10.15.7

## Theory
I think either one of the app's names, or, something else is causing the app logger to crash or hang. I notice I can reliably reproduce it when I switch to an emacs window.

### PR DESCRIPTION
**Pull request by rundong08**
(1) The macOS app logger now works on Emacs
(2) Even if the applescript of the logger failed, the app logger won't
    crash.

Fixes #84

### CODE REVIEW

File: pal_event_server/lib/src/loggers/app_usage/macos/macos_helper.dart [hunk 1]
```diff
@@ -30,21 +30,24 @@ void macOSAppLoggerIsolate(SendPort sendPort) {
...
-        if (_prevAppAndWindowName != null && _prevAppAndWindowName.isNotEmpty) {
-          sendPort.send(_prevAppAndWindowName);
-        }
-
-        _prevAppAndWindowName = currAppAndWindowName;
-
-        // Send PacoEvent && APP_USAGE
-        if (resultMap != null) {
-          sendPort.send(resultMap);
+      if (currWindow != '') {
```
Comment (BobEvans) [inline pal_event_server/lib/src/loggers/app_usage/macos/macos_helper.dart:33]: It looks like this changes the app change detection logic? If we get currWindow == '' then that represents a potentially new window, we just don't know which one. So, we still need to track it as a new window.

File: pal_event_server/lib/src/loggers/app_usage/macos/apple_script_util.dart [hunk 2]
```diff
@@ -57,14 +58,9 @@ const scriptArgs = [
   "-e", r'end if',
   "-e", r'else',
   "-e", r'set windowTitle to "__"',
+  "-e", r'set urlText to ""',
```
Comment (BobEvans) [inline pal_event_server/lib/src/loggers/app_usage/macos/apple_script_util.dart:61]: where is urlText consumed?

Comment (rundong08) [reply pal_event_server/lib/src/loggers/app_usage/macos/apple_script_util.dart:61]: It seems not used currently. Should we log it to Paco server or just remove it?

File: pal_event_server/lib/src/loggers/app_usage/macos/macos_helper.dart (hunk 1 above)
Comment (rundong08) [reply pal_event_server/lib/src/loggers/app_usage/macos/macos_helper.dart:33]: I have played with the script a few times and it appears that currWindow=='' usually means the applescript failed with an error. When there is a new window, there is usually at least an app name. And since we query the window every second, if we actually switched to a new window, the switch will be captured in the next few cycles.

File: pal_event_server/lib/src/loggers/app_usage/macos/apple_script_util.dart (hunk 2 above)
Comment (BobEvans) [reply pal_event_server/lib/src/loggers/app_usage/macos/apple_script_util.dart:61]: It is being parsed out in the pal_event_helper I found. So, looks good.
