### PR TITLE
fixes issue #226 enhance allowlist

### LINKED ISSUE #226: augment allowlist
Add a few more

### PR DESCRIPTION
**Pull request by BobEvans**
Fixes #226

### CODE REVIEW

File: pal_event_server/lib/src/allowlist_default_rules.dart [hunk 1]
```diff
@@ -20,7 +20,10 @@ final chatRegex = RegExp(r'\bchat\b', caseSensitive: false);
 final meetRegex = RegExp(r'\bmeet\b', caseSensitive: false);
 final mailRegex = RegExp(r'\bmail\b', caseSensitive: false);
 final calendarRegex = RegExp(r'\bcalendar\b', caseSensitive: false);
+final slidesRegex = RegExp(r'\bslides\b', caseSensitive: false);
```
Comment (rundong08) [inline pal_event_server/lib/src/allowlist_default_rules.dart]: Do we need to make them more specific, e.g. `Google Slides`, `Google Sheets`, etc.  to avoid overcounting. Or is it better this way?

Comment (BobEvans) [reply pal_event_server/lib/src/allowlist_default_rules.dart]: I was trying to capture all instances of mail or calendar originally and followed that same pattern. With Slides and Sheets, perhaps we would be more likely to capture other things we did not want rather than other apps in the same category. I revised it.

File: pal_event_server/lib/src/allowlist_default_rules.dart [hunk 2]
```diff
@@ -64,12 +67,14 @@ List<AllowListRule> createRules() {
   rules.add(AllowListRule.ofAppUsed(r'Brave'));
   rules.add(AllowListRule.ofAppContent(r'Terminal', r'.*'));
   rules.add(AllowListRule.ofAppContent(r'Taqo', r'.*'));
-  rules.add(AllowListRule.ofAppContent(r'.*', r'.*search.*'));
-  rules.add(AllowListRule.ofAppContent(r'.*', 'Mail'));
-  rules.add(AllowListRule.ofAppContent(r'.*', 'Calendar'));
+  rules.add(AllowListRule.ofAppContent(r'.*', 'Google.com - Mail'));
+  rules.add(AllowListRule.ofAppContent(r'.*', 'Google.com - Calendar'));
```
Comment (rundong08) [inline pal_event_server/lib/src/allowlist_default_rules.dart]: I think these rules are applied after `wipeDetailsOnEvent`, so that app content already becomes `Mail` and `Calendar`.

File: pal_event_server/lib/src/allowlist_default_rules.dart (hunk 1 above)
Comment (rundong08) [reply pal_event_server/lib/src/allowlist_default_rules.dart]: Thanks!

File: pal_event_server/lib/src/allowlist_default_rules.dart (hunk 2 above)
Comment (BobEvans) [reply pal_event_server/lib/src/allowlist_default_rules.dart]: Oops. Yes. Fixed.

**Review by rundong08 — APPROVED** [review]
